### ISSUE TITLE
Usint adjutPlot with stem plots

### ISSUE THREAD

**Issue by paulaceccon** [Phlya/adjustText#110]
I'm trying to use this package to help adjust overlapping annotations in a stem plot, but I'm not able to set it properly, I think.

Here's a minimal example of the issue I have:
https://stackoverflow.com/questions/65835978/timeline-of-events-setting-annotation-location/65856798#65856798

**Comment by Phlya** [comment]
Can you please show what exactly you tried with adjust_text that produced a mess?
I can see you are using plt.annotate to add the text to the plot - can you just try plt.text? Adjust_text only supports that.

**Comment by paulaceccon** [comment]
Hi Phyla. First of all thanks for the quick response. I tried the basic:

```
        from adjustText import adjust_text
        adjust_text(texts)
```
and some variations such as using:

```
only_move={'text': 'x'} 
avoid_self = False
```

I changed to plt.text, but no luck.

**Comment by Phlya** [comment]
OK, I have no experience working with datetime plots... But for me adjust_text just gives an error when applied directly to your plot. However is works fine if I convert datetimes to epoch, and then to ints. Otherwise it keeps giving strange errors about being unable to cast strange data types to floats. Your chaotic output instead might be because you are using an older version - I am using what is in master, and also released as a pre-release, just because exactly this sort of behaviour is untested and was supposed to be fixed...
This is what I get with horizontal texts and if I convert to epoch.
![image](https://user-images.githubusercontent.com/2895034/106131281-6981d780-615a-11eb-9458-b3fa03662c53.png)

Now, maybe if you have experience working with datetime plotting, you can help figure out why it's nor working in the master! Would you might upgrading to it and trying again, and then we can discuss what could be going wrong?

**Comment by Phlya** [comment]
I asked about this at the matplotlib discourse:
https://discourse.matplotlib.org/t/transforms-and-datetime-axis/21813

**Comment by Phlya** [comment]
Please see the temporary solution here: https://github.com/matplotlib/matplotlib/issues/19408

I get this output with default settings:
![image](https://user-images.githubusercontent.com/2895034/106392749-36a24280-63eb-11eb-877c-5fad1b9c65b7.png)

Playing with parameters I can make it a bit neater. I'll add an internal fix into adjust_text at some point so it can handle this internally.

**Comment by Phlya** [comment]
If you update to the version form master, it should work!

**Comment by Phlya** [comment]
I'll close the issue, please reopen if there is still a problem for you.
