### ISSUE TITLE
not perform well in multiple subplot

### ISSUE THREAD

**Issue by zealseeker** [Phlya/adjustText#3]
I tried using adjustText in a subplot, but found that it performed not well.
This is the notebook I made: https://github.com/zealseeker/adjustText/blob/iss1/examples/overlapIssue.ipynb

When I plotted only one subplot (111), it worked (no overlapping in plot). But When I plotted 9 subplots in a figure, some subplots performed poorly.
The first figure is the same as the the thrid subplot of the second figure. But the annotations were plotted differently.

**Comment by Phlya** [comment]
Hi zealseeker, thanks for trying it. My guess is that this has to do with different size of the subplot (because that's the only thing that is different really and it can influence overlaps between labels). However if you want to avoid labels moving down, you have to add virtual points below the top of your bars, otherwise there is nothing preventing them from doing it. Let me know if it helps!

**Comment by zealseeker** [comment]
@Phlya unfortunately, even substantial points cannot fix this problem (I have updated the notebook in my repository) . Is it possible and necessary to restrict the moving direction besides axis. For example `only_move={'text':'y+'}` means that the label can only move upward ?

**Comment by Phlya** [comment]
@zealseeker I think you misunderstood what I meant.

First, a comment: you want to have your labels above bars and at their centers. So it's best to specify this when adding texts (`texts.append(ax.text(left,top,'%.3f'%y[j], horizontalalignment='center'))`). (I actually don't understand why you get centered labels if you don't do it...)

And about adding points. You don't need to plot any additional points, but rather supply the `adjust_text` function with virtual points in the x and y parameters. I modified your notebook and created a PR for you to have a look.

I have been thinking about adding this functionality, but haven't found the time to implement it yet.

**Comment by zealseeker** [comment]
@Phlya Thank you. It's a good way to temporarily solve the problem. But acturally I found  that  `horizontalalignment='center'` is not necessary. The labels get centered due to `autoalign='y'`.  Both of `autoalign='y', only_move={'points':'y', 'text':'y'}` are indispensable, or else the labels would run away.
Anyhow, thank you very much and hope the module will be updated and become popular.

**Comment by Phlya** [comment]
@zealseeker Yes, it's actually quite powerful, because you can specify any "restricted" region on the plot, but does require some fiddling with the parameters sometimes.
That's weird, I think this shouldn't happen, because both of them should restrict movement to only along the y axis... I'll look into it when I have time. Also if you don't mind I'd like to add your example to my example notebook, I think this is probably quite a common use case.

I also hope it becomes popular, thank you!
