### ISSUE TITLE
text_from_points affects layout even when no points are provided

### ISSUE THREAD

**Issue by colinmorris** [Phlya/adjustText#5]
Repro:

```python
from adjustText import adjust_text
import numpy as np
from matplotlib import pyplot as plt

np.random.seed(1337)
n = 50
X1, Y1 = np.random.rand(n), .4 + np.random.rand(n)/5
X2, Y2 = .4+np.random.rand(n)/5, np.random.rand(n)

texts = [plt.text(x, y, '1', color='b') for x, y in zip(X1, Y1)]\
  + [plt.text(x, y, '2', color='r') for x, y in zip(X2, Y2)]

adjust_text(texts,
  #np.concatenate([X1, X2]), np.concatenate([Y1, Y2]),
  text_from_points=False,
)

plt.show()
```

When `text_from_points` is set to True, the annotations are separated perfectly. But setting it to False causes a number of text markers to overlap. (However, the result is still better than without calling `adjust_text` at all).

Since, in this example, I'm only passing in texts, and not points, I would think that the value of `text_from_points` should make no difference.

**Comment by colinmorris** [comment]
Looking at the code, I can see why this is happening, but it doesn't seem like there's a trivial fix.

I would even be happy if overriding `text_from_points` just raised a ValueError (or a Warning) if no points were provided. This bug tripped me up because I had started out passing in points, then tried turning off `text_from_points`, and later stopped passing in points, but left the setting of `text_from_points`, thinking it'd make no difference. It took me a while to figure out why my layout was looking bad - if it had just emitted an error/warning, it would have saved me some debugging.

**Comment by Phlya** [comment]
Hi Colin,

I think there is some misunderstanding here - `text_from_points` is supposed to affect the layout even without additionally specified points, because it treats original coordinates of texts as points as well, not only the coordinates provided by `x` and `y` arguments. This should make it easier to use for the simplest use case of just labelling some points on a scatterplot - you wouldn't want the texts to cover your data (arguably, it's even more important than preventing overlaps of texts), and this way you need to simply provide the text objects. Sorry if this is not clear! I need to invest some time to make a proper documentation I guess...
Maybe the text coordinates should be treated as a special group of coordinates, and optionally it can be excluded from the algorithm while keeping the additional points, and I would be happy to merge a PR providing such functionality, provided that default behaviour stays the same.

**Comment by colinmorris** [comment]
Hi Ilya,

Have you tried running the example? Maybe the more salient point here is that, with `text_from_points` set to False, the texts no longer seem to properly repel each other. `text_from_text` is still True, but the text labels end up overlapping with one another.

I even tried ramping up `force_text` to 1.0, and setting expand_text to `(2.0, 2.0)`, but I still get some significant overlap.

**Comment by Phlya** [comment]
Yes, I see what you mean. Well, I have noticed that such things can happen, but always assumed that just the algorithm isn't perfect and the process of adjustment is quite complicated, so these small changes can affect the outcome quite a lot... But now with your example it seems like you are right and there is something worse going on. You are saying you had a look at the code - do you see where the problem is coming from? I'll try to look into it, thanks for reporting.

**Comment by Phlya** [comment]
Ha! I found the bug, it was a simple typo in the calculation of quality in case of `text_from_points=False`.  Could you please pull the latest version and check whether it helps?

**Comment by colinmorris** [comment]
Oh, I only got as far as seeing that if x and y weren't provided, they'd be set to the original x and y positions of the text (which was enough for me to understand why `text_from_points` was doing anything even though I hadn't provided points). I didn't look any deeper than that.

**Comment by colinmorris** [comment]
Yup, looks like that fixed it. Thanks!

**Comment by Phlya** [comment]
Great! Thanks again for reporting.
