### ISSUE TITLE
Add polar graph support

### ISSUE THREAD

**Issue by ryananeff** [Phlya/adjustText#62]
Currently I am working with a polar scatter plot and would appreciate label adjustment!

**Comment by Phlya** [comment]
Hi, I think it should work with polar plots, can you show an example where it doesn't?

**Comment by nosarcasm** [comment]
Here is a test example https://gist.github.com/nosarcasm/452ec450482a3f2761215640f1f86654

Maybe it doesn't know it is in polar mode?

**Comment by Phlya** [comment]
Right, I see, thanks. I guess it means it doesn't actually work with polar plots - I never properly tested it... Sorry, this would require a bit of work, and I am quite busy at the moment, don't know when I will find the time.
Looks like the autoalignment works though, that's something...

**Comment by nosarcasm** [comment]
What would such a fix entail? Wondering if this is just something that can be fixed by converting to cartesian coordinates before layout and then converting back or something worse...

**Comment by Phlya** [comment]
I am starting to think the best and most general way to deal with this would be to perform all operations on Axes coordinates instead of Data coordinates. This way there shouldn't be any issues with unusual axes coordinates or coordinate systems. In theory it should be enough to change the transforms across the code, but these things are never as simple as one imagines... I'd be delighted if you wanted to give this a go, of course!

**Comment by nosarcasm** [comment]
I switched all coordinates over to display coordinates (which are pixels), seems to work well. FYI, you may find that the precision/expansion values in the Examples.ipynb may need to be tweaked now.
