### ISSUE TITLE
Can't find the right combination of parameters to prevent text from overlapping

### ISSUE THREAD

**Issue by slochower** [Phlya/adjustText#63]
I know this sounds a really vague, but I'm having difficulty finding the right set of parameters that will prevent `adjust_text` from putting labels on top of each other, especially when points are close together. I've tried increasing `force_text`, `force_points`, `expand_text` and `expand_points` in various combinations without success. I've created a minimal [example](http://nbviewer.jupyter.org/gist/slochower/eb41d8ec06330e6c46cb365e661cb19c) to reproduce the problem; there is tons of white space in the graph and I wouldn't mind if the labels used some of that. I've also tried increasing `lim` and decreasing `precision`.

![image](https://user-images.githubusercontent.com/5393995/45769557-d6811c00-bbf4-11e8-9d02-77eb47d7903a.png)

For comparison, `ggrepel` works well for this example (using `force = 2` and `box.padding = 1`). 
![image](https://user-images.githubusercontent.com/5393995/45768987-265ee380-bbf3-11e8-80b6-316327cb55b9.png)

Edit: updated minimal example.

**Comment by Phlya** [comment]
Hi. It works quite well with all default parameters for me - except for one fully overlapping pair of labels:
![image](https://user-images.githubusercontent.com/2895034/45852307-01738900-bd37-11e8-9298-8f2ac3506d3f.png)
That is due to the fact that their coordinates are exactly the same. Normally this should be solved during autoalignment (and it did separate the third label with the same coordinates), but here they are too close to the edge of the axes and are right next to other points/labels, so this fails, because there are only so many options how a text can be aligned. So the easiest solution is to slightly increase the axes limits, let's say -0.1 instead of -0.05:
![image](https://user-images.githubusercontent.com/2895034/45852371-66c77a00-bd37-11e8-9984-238bdfb0427a.png)

I'll leave the fine-tuning for you, but just taking your force changes actually speeds up the algorithm significantly in this case, and also leads to a good result:
![image](https://user-images.githubusercontent.com/2895034/45852433-bc038b80-bd37-11e8-94a1-78c796011369.png)

An alternative solution to fully overlapping labels is adding a tiny (random, or not) shift to one or more of these points, so that visibly the change is unnoticed, but the algorithm can actually do something with them

Hope this helps!

**Comment by Phlya** [comment]
I'm very curious how ggrepel deals with these cases, actually... Will have to have a look at their code, although I don't know R well.

**Comment by slochower** [comment]
Huh, you are correct! I initially had a more complicated example, started messing the parameters, and then pruned it down here. But you are correct that the default settings do an okay job here. I agree that increasing the axis limits helps even further, although I still contend it would be nice to use some of the upper half of the graph for the labels. Feel free to close the issue.

**Comment by Phlya** [comment]
Another option without increasing axes limits is to increase the size of the figure - and, actually, your plot from R is physically bigger.
![image](https://user-images.githubusercontent.com/2895034/45865815-a19cd280-bd76-11e8-8e85-9fd9933e6e46.png)

I agree that there is a lot of whitespace that could be used, however normally I would prefer for the labels to stay as close to their points as possible... This is especially important in more complicated plots, where if texts fly far away their connectors to the points can start crossing, that is ugly and confusing and best avoided.
